### ISSUE TITLE
Failed to process events on room <room>: TypeError: recvData.message.contains is not a function

### ISSUE THREAD

**Issue by realJoshByrnes** [MSNLD/msnld-matrix#1]
Failed to process events on room !gtZJlbtqaPXfStlVxi:msnld.com: TypeError: recvData.message.contains is not a function
    at MatrixClientEmitter.<anonymous> (file:///C:/Users/jd/Documents/Projects/msnld-matrix/index.js:14:30)
    at MatrixClientEmitter.emit (node:events:513:28)
    at matrixClient.onRoomTimeline (file:///C:/Users/jd/Documents/Projects/msnld-matrix/matrixClient.js:92:33)
    at MatrixClient.emit (node:events:513:28)
    at MatrixClient.emit (C:\Users\jd\Documents\Projects\msnld-matrix\node_modules\matrix-js-sdk\lib\models\typed-event-emitter.js:43:18)
    at Room.forSource (C:\Users\jd\Documents\Projects\msnld-matrix\node_modules\matrix-js-sdk\lib\ReEmitter.js:59:21)
    at Room.emit (node:events:513:28)
    at Room.emit (C:\Users\jd\Documents\Projects\msnld-matrix\node_modules\matrix-js-sdk\lib\models\typed-event-emitter.js:43:18) 
    at EventTimelineSet.forSource (C:\Users\jd\Documents\Projects\msnld-matrix\node_modules\matrix-js-sdk\lib\ReEmitter.js:59:21) 
    at EventTimelineSet.emit (node:events:513:28)

**Comment by realJoshByrnes** [comment]
@jyonxo : Did you mean `indexOf('string') !== -1`?

**Comment by realJoshByrnes** [comment]
Issue seems to be revolved with TS codebase. Closing.
